# files of nboard
NBD_SRC = $(NBOARD_HOME)/src
NBD_SRCS := $(shell find $(NBD_SRC) -name "*.cpp")
NBD_LIB = $(NBOARD_HOME)/include
INC_PATH += $(NBD_LIB)

NBD_DST_DIR = $(NBOARD_HOME)/build
NBD_OBJS := $(addprefix $(NBD_DST_DIR)/, $(addsuffix .o, $(basename $(notdir $(NBD_SRCS)))))

# The archive of nvboard
NBD_ARCHIVE = $(NBD_DST_DIR)/NVBOARD.a

$(NBD_DST_DIR)/%.o: $(NBD_SRC)/%.cpp
	@echo + CXX "->" NBOARD_HOME/$(shell realpath $< --relative-to $(NBOARD_HOME))
	@mkdir -p $(dir $@)
	@$(OBJCACHE) $(CXX) $(CXXFLAGS) $(CPPFLAGS) $(OPT_FAST) -I$(NBD_LIB) -c -o $@ $<

# Build the archive of nvboar
$(NBD_ARCHIVE): $(NBD_OBJS)
	@echo + AR "->" $(shell realpath $@ --relative-to $(NBOARD_HOME))
	@ar rcs $(NBD_ARCHIVE) $(NBD_OBJS)

# Rule (`#include` dependencies): paste in `.d` files generated by gcc on `-MMD`
-include $(NBD_OBJS:.o=.d)

.PHONY: archive nbd-clean

archive: $(NBD_ARCHIVE) 

nbd-clean:
	rm -rf $(NBD_DST_DIR)
